export const translations: Record<string, string> = {
  EMAIL_VALIDATION_ERROR: "Must be an email",
  REQUIRED_FIELD: "This field is required",
  FULL_NAME_MIN_LENGTH_VALIDATION_ERROR: "too short",
  FULL_NAME_MAX_LENGTH_VALIDATION_ERROR: "very long",
  LOGIN_TITLE: "Login",
  LOGIN_DESCRIPTION: "Enter your email below to login to your account.",
  LOGIN_BUTTON_LABEL: "Sign in",
  LOGIN_NEW_USER_LABEL: "New here?",
  LOGIN_SIGNUP_REDIRECT_LABEL: "Sign up",
  LOGIN_EMAIL_FIELD_LABEL: "Email",
  LOGIN_PASSWORD_FIELD_LABEL: "Password",
  SIGNUP_TITLE: "Sign Up",
  SIGNUP_DESCRIPTION: "Enter your information to create an account",
  SIGNUP_BUTTON_LABEL: "Create an account",
  SIGNUP_EMAIL_FIELD_LABEL: "Email",
  SIGNUP_PASSWORD_FIELD_LABEL: "Password",
  SIGNUP_FULL_NAME_FIELD_LABEL: "Full Name",
  SIGNUP_ALREADY_HAVE_AN_ACCOUNT_LABEL: "Already have an account?",
  SIGNUP_LOGIN_REDIRECT_LABEL: "Sign in",
  DASHBOARD: "Dashboard",
  EMPLOYEES: "Employees",
  SALARIES: "Salaries",
  EMPLOYEES_TABLE_TITLE: "Employees",
  EMPLOYEES_TABLE_DESCRIPTION: "Easily add, update and remove employees",
  SALARIES_TABLE_TITLE: "Salaries",
  SALARIES_TABLE_DESCRIPTION:
    "You must specify the salary month and year for each employee salary processing, Employees without specified month and year details will be excluded from the session",
  EMPLOYEES_PAGE_TITLE: "Employee Management",
  EMPLOYEES_PAGE_DESCRIPTION: "Easily add, update and remove employees.",
  TABLE_EMPTY_TABLE: "No Data Available",
  EMPLOYEES_TABLE_STAFF_ID_FIELD: "Staff ID",
  EMPLOYEES_TABLE_NAME_FIELD: "Full Name",
  EMPLOYEES_TABLE_JOINING_DATE_FIELD: "Joining Date",
  EMPLOYEES_TABLE_BASIC_SALARY_FIELD: "Basic Salary",
  EMPLOYEES_TABLE_ALLOWANCES_FIELD: "Allowances",
  EMPLOYEES_TABLE_ACTIONS_FIELD: "Actions",
  SALARIES_TABLE_STAFF_ID_FIELD: "Staff ID",
  SALARIES_TABLE_NAME_FIELD: "Full Name",
  SALARIES_TABLE_JOINING_DATE_FIELD: "Joining Date",
  SALARIES_TABLE_PAY_DATE_FIELD: "Pay Date",
  SALARIES_TABLE_BASIC_SALARY_FIELD: "Basic Salary",
  SALARIES_TABLE_ALLOWANCES_FIELD: "Allowances",
  SALARIES_TABLE_ACTIONS_LABEL: "Actions",
  SALARIES_TABLE_EDIT_ACTION_LABEL: "Edit",
  SALARIES_TABLE_DELETE_ACTION_LABEL: "Delete",
  SALARIES_PAGE_TITLE: "Salaries Management",
  SALARIES_PAGE_DESCRIPTION:
    "Easily update, pay and manage employees salaries.",
  SALARIES_TABLE_ADDITIONS_FIELD: "Additions",
  SALARIES_TABLE_DEDUCTIONS_FIELD: "Deductions",
  ADD_EMPLOYEE: "Add employee",
  PICK_A_DATE: "Pick a date",
  HOUSE_RENT: "House Rent",
  CHILDREN_EDUCATION: "Children Education",
  CONVENANCE: "Conveyance",
  HELPER_ASSISTANT: "Helper/Assistant",
  BOOKS_PERIODICALS: "Books or periodicals",
  FOOD_COUPONS: "Food coupons",
  LEAVE_TRAVEL_CONCESSION_ASSISTANCE: "Leave Travel Concession or Assistance",
  MULTI_SELECT_PLACEHOLDER: "Select options...",
  ADD_EMPLOYEE_DESCRIPTION:
    "Add employee information here. Click add when you're done.",
  CANCEL: "Cancel",
  CONTINUE: "Continue",
  DELETE_EMPLOYEE: "Are you sure you want to remove employee?",
  DELETE_EMPLOYEE_DESCRIPTION:
    "This action cannot be undone. This will permanently delete employee account.",
  DELETE: "Delete",
  EDIT: "Edit",
  ADD: "Add",
  EDIT_EMPLOYEE: "Edit Employee",
  EDIT_EMPLOYEE_DESCRIPTION:
    "Update employee information here. Click save when you're done.",
  INCOME_TAX: "Income tax",
  STATE_LOCAL_INCOME_TAX: "State and local income tax",
  HEALTH_INSURANCE: "health insurance",
  LIFE_INSURANCE_AND_DISABILITY_PLAN: "life insurance and disability plan",
  RETIREMENT_PLAN: "retirement plan",
  ANNUAL_BONUS: "Annual Bonus",
  HOLIDAY_BONUS: "Holiday bonus",
  PERFORMANCE_BONUS: "Performance bonus",
  SIGN_ON_BONUS: "Sign on bonus",
  TOTAL: "total",
  SUBMIT: "Submit",
  SAVE: "Save",
  EDIT_MODE: "Update Payment Information",
  PAY: "Process Payment",
};
