export const translations = {
  EMAIL_VALIDATION_ERROR: "Must be an email",
  REQUIRED_FIELD: "This field is required",
  FULL_NAME_MIN_LENGTH_VALIDATION_ERROR: "too short",
  FULL_NAME_MAX_LENGTH_VALIDATION_ERROR: "very long",
  LOGIN_TITLE: "Login",
  LOGIN_DESCRIPTION: "Enter your email below to login to your account.",
  LOGIN_BUTTON_LABEL: "Sign in",
  LOGIN_NEW_USER_LABEL: "New here?",
  LOGIN_SIGNUP_REDIRECT_LABEL: "Sign up",
  LOGIN_EMAIL_FIELD_LABEL: "Email",
  LOGIN_PASSWORD_FIELD_LABEL: "Password",
  SIGNUP_TITLE: "Sign Up",
  SIGNUP_DESCRIPTION: "Enter your information to create an account",
  SIGNUP_BUTTON_LABEL: "Create an account",
  SIGNUP_EMAIL_FIELD_LABEL: "Email",
  SIGNUP_PASSWORD_FIELD_LABEL: "Password",
  SIGNUP_FULL_NAME_FIELD_LABEL: "Full Name",
  SIGNUP_ALREADY_HAVE_AN_ACCOUNT_LABEL: "Already have an account?",
  SIGNUP_LOGIN_REDIRECT_LABEL: "Sign in",
  DASHBOARD: "Dashboard",
  EMPLOYEES: "Employees",
  SALARIES: "Salaries",
  EMPLOYEES_TABLE_TITLE: "Employees",
  EMPLOYEES_TABLE_DESCRIPTION: "Easily add, update and remove employees",
  SALARIES_TABLE_TITLE: "Salaries",
  SALARIES_TABLE_DESCRIPTION:
    "Easily update, pay and manage employees salaries",
  EMPLOYEES_PAGE_TITLE: "Employee Management",
  EMPLOYEES_PAGE_DESCRIPTION: "Easily add, update and remove employees.",
  TABLE_EMPTY_TABLE: "No Data Available",
  EMPLOYEES_TABLE_STAFF_ID_FIELD: "Staff ID",
  EMPLOYEES_TABLE_NAME_FIELD: "Full Name",
  EMPLOYEES_TABLE_JOINING_DATE_FIELD: "Joining Date",
  EMPLOYEES_TABLE_BASIC_SALARY_FIELD: "Basic Salary",
  EMPLOYEES_TABLE_ALLOWANCES_FIELD: "Allowances",
  EMPLOYEES_TABLE_ACTIONS_FIELD: "Actions",
  SALARIES_TABLE_STAFF_ID_FIELD: "Staff ID",
  SALARIES_TABLE_NAME_FIELD: "Full Name",
  SALARIES_TABLE_JOINING_DATE_FIELD: "Joining Date",
  SALARIES_TABLE_BASIC_SALARY_FIELD: "Basic Salary",
  SALARIES_TABLE_ALLOWANCES_FIELD: "Allowances",
  SALARIES_TABLE_ACTIONS_LABEL: "Actions",
  SALARIES_TABLE_EDIT_ACTION_LABEL: "Edit",
  SALARIES_TABLE_DELETE_ACTION_LABEL: "Delete",
  SALARIES_PAGE_TITLE: "Salaries Management",
  SALARIES_PAGE_DESCRIPTION:
    "Easily update, pay and manage employees salaries.",
  SALARIES_TABLE_ADDITIONS_FIELD: "Additions",
  SALARIES_TABLE_DEDUCTIONS_FIELD: "Deductions",
};
