export const translations = {
  EMAIL_VALIDATION_ERROR: "Must be an email",
  REQUIRED_FIELD: "This field is required",
  FULL_NAME_MIN_LENGTH_VALIDATION_ERROR: "too short",
  FULL_NAME_MAX_LENGTH_VALIDATION_ERROR: "very long",
  LOGIN_TITLE: "Login",
  LOGIN_DESCRIPTION: "Enter your email below to login to your account.",
  LOGIN_BUTTON_LABEL: "Sign in",
  LOGIN_NEW_USER_LABEL: "New here?",
  LOGIN_SIGNUP_REDIRECT_LABEL: "Sign up",
  LOGIN_EMAIL_FIELD_LABEL: "Email",
  LOGIN_PASSWORD_FIELD_LABEL: "Password",
  SIGNUP_TITLE: "Sign Up",
  SIGNUP_DESCRIPTION: "Enter your information to create an account",
  SIGNUP_BUTTON_LABEL: "Create an account",
  SIGNUP_EMAIL_FIELD_LABEL: "Email",
  SIGNUP_PASSWORD_FIELD_LABEL: "Password",
  SIGNUP_FULL_NAME_FIELD_LABEL: "Full Name",
  SIGNUP_ALREADY_HAVE_AN_ACCOUNT_LABEL: "Already have an account?",
  SIGNUP_LOGIN_REDIRECT_LABEL: "Sign in",
  DASHBOARD: "Dashboard",
  EMPLOYEES: "Employees",
  SALARIES: "Salaries",
};
